/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual_Aeropuerto;

import Visual.Aerolinea.Panel_Datos_Aerolinea;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author MEDAC
 */
public class Panel_Muestra_Datos_Aeropuerto extends javax.swing.JPanel {
    private static final String DRIVER = "com.mysql.cj.jdbc.Driver";
    private static final String URL_CONEXION = "jdbc:mysql://localhost:3306/mydb";
    private static final String USUARIO = "root";
    private static final String PASSWORD = "1234";
    /**
     * Creates new form Panel_Muestra_Datos
     */
    public Panel_Muestra_Datos_Aeropuerto() {
        initComponents();
        mostrarDatosAerolinea();
        
    }
     private void mostrarDatosAerolinea() {
        try {
            Class.forName(DRIVER);
            Connection conn = DriverManager.getConnection(URL_CONEXION, USUARIO, PASSWORD);
            Statement stmt = conn.createStatement();
            String sql = "SELECT * FROM aeropuerto";
            ResultSet rs = stmt.executeQuery(sql);

            // Si hay registros, mostramos el primero
            while (rs.next()) {

                int id = rs.getInt("id_aeropuerto");
                String nom = rs.getString("nombre");
                String ciudad = rs.getString("ciudad");
                String pais = rs.getString("pais");
                String num = rs.getString("numero_pistas");
                System.out.println(id);
                Panel_Datos_Aeropuerto panel = new Panel_Datos_Aeropuerto();
                panel.getLblid().setText(String.valueOf(id));
                panel.getLblnombre().setText(nom);
                panel.getLblciudad().setText(String.valueOf(ciudad));
                panel.getLblpais().setText(String.valueOf(pais));
                panel.getLblpsitas().setText(num);

                add(panel);

            }
            //add(listaComponentes);
            rs.close();
            stmt.close();
            conn.close();

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Error al conectar con la base de datos: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
