/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual_Pasajero;

import Visual_Empleado.Panel_Datos_Empleado;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author MEDAC
 */
public class Panel_Muestra_Datos_Pasajero extends javax.swing.JPanel {
    private static final String DRIVER = "com.mysql.cj.jdbc.Driver";
    private static final String URL_CONEXION = "jdbc:mysql://localhost:3306/mydb";
    private static final String USUARIO = "root";
    private static final String PASSWORD = "1234";
    /**
     * Creates new form Panel_Muestra_Datos_Pasajero
     */
    public Panel_Muestra_Datos_Pasajero() {
        initComponents();
        mostrarDatospasajero();
    }
private void mostrarDatospasajero() {
        try {
            Class.forName(DRIVER);
            Connection conn = DriverManager.getConnection(URL_CONEXION, USUARIO, PASSWORD);
            Statement stmt = conn.createStatement();
            String sql = "SELECT * FROM pasajero";
            ResultSet rs = stmt.executeQuery(sql);



            while (rs.next()) {

                String dni = rs.getString("dni");
                String nombre = rs.getString("nombre");
                String apellido = rs.getString("apellido");
                int telefono = rs.getInt("telefono");
                Panel_Datos_Pasajero panel = new Panel_Datos_Pasajero();
                panel.getLbldni().setText(dni);
                panel.getLblnombre().setText(nombre);
                panel.getLblapellido().setText(apellido);
                panel.getLbltelf().setText(String.valueOf(telefono));
                
                add(panel);

            }
            //add(listaComponentes);
            rs.close();
            stmt.close();
            conn.close();

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Error al conectar con la base de datos: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
